// app
export const SET_ACTIVE_PATH = 'SET_ACTIVE_PATH'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const GET_STATS_DATA = 'GET_STATS_DATA'
// activity
export const GET_ACTICITY_LIST = 'GET_ACTIVITY_LIST'
export const GET_BANNER_LIST = 'GET_BANNER_LIST'
// system
export const GET_TEMPLATE_LIST = 'GET_TEMPLATE_LIST'
export const GET_ALL_TEMPLATES = 'GET_ALL_TEMPLATES'
export const GET_AGENT_LEVEL_LIST = 'GET_AGENT_LEVEL_LIST'
export const GET_AGENTS_LIST = 'GET_AGENTS_LIST'
export const GET_HELP_LIST = 'GET_HELP_LIST'
export const GET_PERMISSION_LIST = 'GET_PERMISSION_LIST'
export const GET_ROLE_LIST = 'GET_ROLE_LIST'
export const GET_SIGN_LIST = 'GET_SIGN_LIST'
// commodity
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
// order
export const GET_ORDER_LIST = 'GET_ORDER_LIST'
export const GET_WITHDRAW = 'GET_WITHDRAW'
export const GET_COMMON_LIST = 'GET_COMMON_LIST'
// user
export const GET_USER_LIST = 'GET_USER_LIST'
export const GET_AGENT_LIST = 'GET_AGENT_LIST'
// market
export const GET_TRIBUTION_LIST = 'GET_TRIBUTION_LIST'
export const GET_USECONPONLIST = 'GET_USECONPONLIST'
export const GETCOUPONCENTERLIST = 'GETCOUPONCENTERLIST'
export const SETACTIVITYDATA = 'SETACTIVITYDATA'
export const SETCOUPONROW = 'SETCOUPONROW'
export const GET_COUPON_LIST = 'GET_COUPON_LIST' // 优惠卷
